// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static Future<FirebaseOptions> get currentPlatform async {
    await dotenv.load();

    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['API_KEY']!,
    appId: dotenv.env['API_ID_WEB']!,
    messagingSenderId: dotenv.env['APP_MESSAGING_SENDER_ID']!,
    projectId: dotenv.env['APP_PROJECT_ID']!,
    authDomain: dotenv.env['APP_AUTH_DOMAIN']!,
    storageBucket: dotenv.env['APP_STORAGE_BUCKET']!,
    measurementId: 'G-GX4E0LKFZQ',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['API_KEY']!,
    appId: dotenv.env['APP_ID_ANDROID']!,
    messagingSenderId: dotenv.env['APP_MESSAGING_SENDER_ID']!,
    projectId: dotenv.env['APP_PROJECT_ID']!,
    storageBucket: dotenv.env['APP_STORAGE_BUCKET']!,
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['API_KEY']!,
    appId: dotenv.env['API_ID_IOS']!,
    messagingSenderId: dotenv.env['APP_MESSAGING_SENDER_ID']!,
    projectId: dotenv.env['APP_PROJECT_ID']!,
    storageBucket: dotenv.env['APP_STORAGE_BUCKET']!,
    iosBundleId: dotenv.env['APP_BUNDLE_IOS_ID']!,
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['API_KEY']!,
    appId: dotenv.env['API_ID_IOS']!,
    messagingSenderId: dotenv.env['APP_MESSAGING_SENDER_ID']!,
    projectId: dotenv.env['APP_PROJECT_ID']!,
    storageBucket: dotenv.env['APP_STORAGE_BUCKET']!,
    iosBundleId: dotenv.env['APP_BUNDLE_IOS_ID']!,
  );
}
