// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYDWsKeBbfcLUTQhT5wVUL6vEZBMvXCpA',
    appId: '1:265082619570:web:09ecad6dcee526c46b6bab',
    messagingSenderId: '265082619570',
    projectId: 'messageapp-5f57a',
    authDomain: 'messageapp-5f57a.firebaseapp.com',
    storageBucket: 'messageapp-5f57a.appspot.com',
    measurementId: 'G-GX4E0LKFZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdWV84H_a553e29pKNyO-48NwCT9elyrI',
    appId: '1:265082619570:android:b6a02c0e17ac5b756b6bab',
    messagingSenderId: '265082619570',
    projectId: 'messageapp-5f57a',
    storageBucket: 'messageapp-5f57a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKeVzbNSF18-YqLBbs4MFJI69rxNmWiyQ',
    appId: '1:265082619570:ios:b541c86bf9fb91546b6bab',
    messagingSenderId: '265082619570',
    projectId: 'messageapp-5f57a',
    storageBucket: 'messageapp-5f57a.appspot.com',
    iosBundleId: 'com.example.messageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKeVzbNSF18-YqLBbs4MFJI69rxNmWiyQ',
    appId: '1:265082619570:ios:b541c86bf9fb91546b6bab',
    messagingSenderId: '265082619570',
    projectId: 'messageapp-5f57a',
    storageBucket: 'messageapp-5f57a.appspot.com',
    iosBundleId: 'com.example.messageApp',
  );
}
